apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pages
  name: pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
  strategy: {}
  template:
    metadata:
      labels:
        app: pages
    spec:
      containers:
        - image: dellcloud/pages:service
          name: pages
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080